airflow_db:
  target: dev
  outputs:
    dev:
      type: postgres
      host: aws-0-ap-southeast-1.pooler.supabase.com
      user: postgres.ryghjqerglvkqxrjpcyp
      password: "{{ env_var('SUPABASE_PASSWORD') }}"
      port: 6543
      dbname: postgres
      schema: ota_data_prod
      threads: 4
